In [2]:
import numpy as np
import pandas as pd

In [3]:
file_path = "C:/Users/82108/Desktop/jw/프로젝트/반려동물등록현황전처리전/서울특별시동대문구반려동물등록현황20201014.csv"
df_raw = pd.read_csv(file_path, encoding='euc-kr')
# 파일불러오기 
# 인코딩 문제 발생, 현재 파일이 EUC-KR로 인코딩되어 있으므로 encoding='euc-kr'으로 지정

In [4]:
# 원본 데이터
df_raw.head()

,읍면동(법정동),등록주체_시군구,등록주체_대행업체,등록주체_기타(이벤트 등),등록형태_내장형RFID,등록형태_외장형RFID,등록형태_인식표RFID,등록품종수,동물소유자수,동물소유자당동물등록수,총등록수,데이터기준일자
0,신설동,6.0,188.0,0.0,70.0,103.0,21.0,32.0,147.0,1.32,194.0,2020-10-14
1,용두동,70.0,1275.0,2.0,508.0,721.0,118.0,64.0,1025.0,1.31,1347.0,2020-10-14
2,이문동,52.0,2320.0,1.0,1034.0,1196.0,143.0,67.0,1344.0,1.77,2373.0,2020-10-14
3,장안동,133.0,3450.0,1.0,1508.0,1871.0,205.0,78.0,2745.0,1.31,3584.0,2020-10-14
4,전농동,76.0,1882.0,2.0,1030.0,800.0,130.0,67.0,1559.0,1.26,1960.0,2020-10-14

In [5]:
# 원본데이터 복사
dongdaemun = df_raw.copy()

In [6]:
# 필요한 컬럼만 남기기
dongdaemun = dongdaemun[['읍면동(법정동)','동물소유자수','동물소유자당동물등록수','총등록수']]

# 컬럼명 변경하기
dongdaemun.rename(columns={'읍면동(법정동)':'Location',
                            '동물소유자수':'Pet_Owners',
                            '동물소유자당동물등록수':'Registrations_per_Pet_Owner',
                            '총등록수':'Total_Registrations'},
                  inplace=True)

dongdaemun

   Location  Pet_Owners  Registrations_per_Pet_Owner  Total_Registrations
0       신설동       147.0                         1.32                194.0
1       용두동      1025.0                         1.31               1347.0
2       이문동      1344.0                         1.77               2373.0
3       장안동      2745.0                         1.31               3584.0
4       전농동      1559.0                         1.26               1960.0
5       제기동       901.0                         1.33               1194.0
6       회기동       285.0                         1.18                335.0
7       휘경동      1130.0                         1.25               1413.0
8      답십리동      1873.0                         1.36               2538.0
9      청량리동       659.0                         1.32                873.0
10      NaN         NaN                          NaN                  NaN

In [9]:
# 결측치 제거
dongdaemun.dropna(inplace=True)
dongdaemun

  Location  Pet_Owners  Registrations_per_Pet_Owner  Total_Registrations
0      신설동       147.0                         1.32                194.0
1      용두동      1025.0                         1.31               1347.0
2      이문동      1344.0                         1.77               2373.0
3      장안동      2745.0                         1.31               3584.0
4      전농동      1559.0                         1.26               1960.0
5      제기동       901.0                         1.33               1194.0
6      회기동       285.0                         1.18                335.0
7      휘경동      1130.0                         1.25               1413.0
8     답십리동      1873.0                         1.36               2538.0
9     청량리동       659.0                         1.32                873.0

In [10]:
# 파일 저장하기
dongdaemun.to_csv("./dongdaemun.csv")