In [20]:
import numpy as np
import pandas as pd

In [21]:
file_path = "C:/Users/82108/Desktop/jw/프로젝트/반려동물등록현황전처리전/서울특별시_동작구_반려동물등록현황_20230825.csv"
df_raw = pd.read_csv(file_path, encoding='euc-kr')
# 파일불러오기 
# 인코딩 문제 발생, 현재 파일이 EUC-KR로 인코딩되어 있으므로 encoding='euc-kr'으로 지정

In [22]:
# 원본 데이터
df_raw.head()

         시군구  법정동   내장형   외장형  인식표  반려동물총계  등록품종수  동물소유자수  동물소유자당동물등록수
0  서울특별시 동작구   본동   278   240   67     585     55     462         1.27
1  서울특별시 동작구  대방동   825   930  224    1979     73    1579         1.25
2  서울특별시 동작구  동작동   171   148   23     342     42     283         1.21
3  서울특별시 동작구  사당동  2336  2345  445    5126    101    3871         1.32
4  서울특별시 동작구  상도동  2903  2623  593    6119     97    4738         1.29

In [23]:
# 원본데이터 복사
dongjak = df_raw.copy()

In [24]:
# 필요한 컬럼만 남기기
dongjak = dongjak[['법정동','동물소유자수','동물소유자당동물등록수','반려동물총계']]

# 컬럼명 변경하기
dongjak.rename(columns={'법정동':'Location',
                            '동물소유자수':'Pet_Owners',
                            '동물소유자당동물등록수':'Registrations_per_Pet_Owner',
                            '반려동물총계':'Total_Registrations'},
                  inplace=True)

dongjak

  Location  Pet_Owners  Registrations_per_Pet_Owner  Total_Registrations
0       본동         462                         1.27                  585
1      대방동        1579                         1.25                 1979
2      동작동         283                         1.21                  342
3      사당동        3871                         1.32                 5126
4      상도동        4738                         1.29                 6119
5      흑석동        1340                         1.27                 1702
6     상도1동         382                         1.30                  495
7     노량진동        1158                         1.30                 1509
8     신대방동        1888                         1.29                 2438

In [25]:
# 결측치 제거
dongjak.dropna(inplace=True)
dongjak

  Location  Pet_Owners  Registrations_per_Pet_Owner  Total_Registrations
0       본동         462                         1.27                  585
1      대방동        1579                         1.25                 1979
2      동작동         283                         1.21                  342
3      사당동        3871                         1.32                 5126
4      상도동        4738                         1.29                 6119
5      흑석동        1340                         1.27                 1702
6     상도1동         382                         1.30                  495
7     노량진동        1158                         1.30                 1509
8     신대방동        1888                         1.29                 2438

In [28]:
# 파일 저장하기
dongjak.to_csv("./ddongjak.csv")